# Generated by Django 5.2.7 on 2025-11-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_height_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Designates whether this user is approved. Doctors require admin approval before they can login.'),
        ),
    ]
