# Generated by Django 5.2.7 on 2025-12-01 06:34

from django.db import migrations
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorspecialization'),
    ]

    def seed_specializations(apps, schema_editor):
        DoctorSpecialization = apps.get_model('doctors', 'DoctorSpecialization')
        defaults = [
            'General Practice',
            'Cardiology',
            'Dermatology',
            'Pediatrics',
            'Orthopedics',
            'Neurology',
            'Obstetrics & Gynecology',
            'Psychiatry',
            'Ophthalmology',
            'Ear, Nose & Throat',
            'Endocrinology',
            'Gastroenterology',
        ]
        for order, name in enumerate(defaults):
            DoctorSpecialization.objects.get_or_create(
                name=name,
                defaults={
                    'display_order': order,
                    'slug': slugify(name)
                }
            )

    def unseed_specializations(apps, schema_editor):
        DoctorSpecialization = apps.get_model('doctors', 'DoctorSpecialization')
        DoctorSpecialization.objects.all().delete()

    operations = [
        migrations.RunPython(seed_specializations, unseed_specializations),
    ]
